# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

  # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  providers:
    my_provider:
      entity: { class: App:Users, property: name }

  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern:   ^/api
      stateless: true

      guard:
        authenticators:
          - App\Security\TokenAuthenticator

    main:
      anonymous: ~
      logout:
        path: /logout
        target: /
      logout_on_user_change: true

      guard:
        authenticators:
          - App\Security\GoogleAuthenticator

  access_control:
    - { path: ^/app, roles: ROLE_USER }
#    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
      # - { path: ^/profile, roles: ROLE_USER }

knpu_oauth2_client:
  clients:
    google:
      # must be "google" - it activates that type!
      type: google
      # add and configure client_id and client_secret in parameters.yml
      client_id: '%env(resolve:GOOGLE_CLIENT_ID)%'
      client_secret: '%env(resolve:GOOGLE_CLIENT_SECRET)%'
      # a route name you'll create
      redirect_route: connect_google_check
      redirect_params: {}
      # Optional value for sending access_type parameter. More detail: https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters
      # access_type: ''
      # Optional value for sending hd parameter. More detail: https://developers.google.com/identity/protocols/OpenIDConnect#hd-param
      # hosted_domain: ''
      # Optional value for additional fields to be requested from the user profile. If set, these values will be included with the defaults. More details: https://developers.google.com/+/web/api/rest/latest/people
      # user_fields: {}
      # whether to check OAuth2 "state": defaults to true
      # use_state: true